/**
 * Extracts only the UX4G rules this app actually uses.
 *
 * The published bundle is 7.9MB (3.9MB gzipped) covering 3,384 classes, of
 * which we use a few dozen. Shipping all of it would put roughly a minute of
 * download in front of a citizen on a district-town 3G connection — the exact
 * user this product is for. Tailwind cannot tree-shake it because it arrives
 * as pre-built CSS, so we slice it here instead.
 *
 * Re-run after using a new ux4g- class, then commit the output:
 *   node scripts/extract-ux4g.mjs
 */
import { readFileSync, writeFileSync } from "node:fs";
import { execSync } from "node:child_process";

const SOURCE = "node_modules/ux4g-web-components/styles/ux4g.css";
const OUT = "app/ux4g.css";

// Every ux4g- class named anywhere in our own source.
const used = new Set();
const grep = execSync(
  `grep -rhoE "ux4g-[a-zA-Z0-9-]+" app components lib --include=*.tsx --include=*.ts || true`,
  { encoding: "utf8", maxBuffer: 32 * 1024 * 1024 }
);
for (const match of grep.split(/\s+/)) if (match) used.add(match.trim());

/*
 * Classes built from a template literal — `ux4g-btn-${variant}` — cannot be
 * found by grep, so the components that take a variant or size prop declare
 * their full range here. Without this the class exists in the DOM and its rule
 * is missing, which renders an unstyled control rather than failing loudly.
 */
const DYNAMIC = {
  "ux4g-btn": [
    "primary", "outline-primary", "tonal-primary", "text-primary",
    "danger", "outline-danger",
    "xl", "lg", "md", "sm",
  ],
};
for (const [base, suffixes] of Object.entries(DYNAMIC)) {
  used.add(base);
  for (const suffix of suffixes) used.add(`${base}-${suffix}`);
}

const css = readFileSync(SOURCE, "utf8");

// Keep every :root block: that is where the design tokens live, and a
// component rule referencing a dropped token would render wrong rather than
// simply unstyled.
const kept = [];
let depth = 0;
let start = 0;
let inString = false;
let stringChar = "";

for (let i = 0; i < css.length; i++) {
  const ch = css[i];
  if (inString) {
    if (ch === stringChar && css[i - 1] !== "\\") inString = false;
    continue;
  }
  if (ch === '"' || ch === "'") {
    inString = true;
    stringChar = ch;
    continue;
  }
  if (ch === "{") {
    if (depth === 0) start = i;
    depth++;
  } else if (ch === "}") {
    depth--;
    if (depth === 0) {
      const selector = css.slice(start, i).split("{")[0];
      const prelude = css.slice(0, start).split("}").pop() ?? "";
      const rule = css.slice(css.lastIndexOf("}", start) + 1, i + 1);
      const head = prelude.trim();

      const isRoot = head.includes(":root");
      const isAtRule = head.startsWith("@");
      const classes = head.match(/\.ux4g-[a-zA-Z0-9-]+/g) ?? [];
      const usesOurs = classes.some((c) => used.has(c.slice(1)));

      // Drop @font-face entirely: 6.5MB of the bundle is base64-embedded
      // fonts, and this app already loads Atkinson Hyperlegible, chosen for
      // legibility, plus a Devanagari face for Hindi. UX4G's faces would be
      // downloaded and never used.
      const isFontFace = head.startsWith("@font-face");
      if (!isFontFace && (isRoot || isAtRule || usesOurs)) kept.push(rule.trim());
      void selector;
    }
  }
}

const output = `/*
 * Generated by scripts/extract-ux4g.mjs — do not edit by hand.
 *
 * Only the UX4G rules this app uses, plus all :root token blocks. Regenerate
 * after adopting a new ux4g- class.
 */
${kept.join("\n")}
`;

writeFileSync(OUT, output);

const before = Buffer.byteLength(css) / 1024 / 1024;
const after = Buffer.byteLength(output) / 1024;
console.log(`ux4g: ${used.size} classes used`);
console.log(`ux4g: ${before.toFixed(1)} MB -> ${after.toFixed(1)} KB (${kept.length} rules kept)`);
